apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      version: ">0.0.0"
  interval: 1m
  values:
    replicaCount: 1
    ingress:
      enabled: true
      className: "traefik"
      hosts:
        - host: podinfo.ppetrov.info
          paths:
            - path: /
              pathType: ImplementationSpecific